[[ranks]]
  tier = 0
  numAffixes = 0
  defaultColor = 0xffffff
  chance = 1.0
  growthFactor = 0
  effects = []
  presetAffixes = []
[[ranks]]
  tier = 1
  numAffixes = 1
  defaultColor = 0xffff00
  chance = 0.05
  growthFactor = 1
  effects = []
  presetAffixes = []
[[ranks]]
  tier = 2
  numAffixes = 2
  defaultColor = 0x55ff55
  chance = 0.2
  growthFactor = 4
  effects = []
  presetAffixes = []
[[ranks]]
  tier = 3
  numAffixes = 3
  defaultColor = 0x55ffff
  chance = 0.2
  growthFactor = 9
  effects = []
  presetAffixes = []
[[ranks]]
  tier = 4
  numAffixes = 4
  defaultColor = 0x00aa00
  chance = 0.2
  growthFactor = 16
  effects = []
  presetAffixes = []
[[ranks]]
  tier = 5
  numAffixes = 5
  defaultColor = 0x5555ff
  chance = 0.2
  growthFactor = 25
  effects = []
  presetAffixes = []
[[ranks]]
  tier = 6
  numAffixes = 6
  defaultColor = 0xaa00aa
  chance = 0.2
  growthFactor = 36
  effects = []
  presetAffixes = []
[[ranks]]
  tier = 7
  numAffixes = 7
  defaultColor = 0xaa0000
  chance = 0.2
  growthFactor = 49
  effects = []
  presetAffixes = []
