
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 450392
	#The name of the modpack
	modpackName = "DIMENSIONS_AND_DUNGEONEERING"
	#The version of the modpack
	modpackVersion = "0.23"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

