
#Project: Vibrant Journeys settings
[Settings]

	#World Gen Settings
	[Settings."World Gen"]
		#Denser river grass
		moreGrassInRivers = true
		fallenTrees = true
		seaOats = true
		#Seagrass in lakes
		moreSeagrass = true
		barkMushrooms = true
		netherNettles = true
		glowcap = true
		bushes = true
		cobwebs = true
		cattails = true
		shortGrass = true
		beachGrass = true

		[Settings."World Gen".Groundcover]
			iceChunks = true
			#Groundcover Biome Blacklist, example: ["minecraft:plains", "minecraft:beach"]
			groundcoverBlacklist = []
			rocks = true
			seashells = true
			bones = true
			twigs = true
			# % chance of groundcover placement
			#Range: 0 ~ 100
			groundcoverChance = 100
			pinecones = true
			fallenLeaves = true
			charredBones = true

	#Biome Settings
	[Settings.Biomes]
		overgrown_spires = true
		verdant_sands = true
		boreal_forest = true
		snowy_boreal_forest = true
		redwoods = true
		snowy_redwoods = true
		redwood_peaks = true
		pine_meadows = true
		alpine_heights = true
		boreal_plateau = true
		aspen_grove = true
		mangrove_marsh = true
		willow_wetlands = true
		baobab_fields = true
		prairie = true
		blossoming_fields = true
		autumnal_coniferous_forest = true
		crimson_thicket = true
		desert_shrubland = true
		red_rock_valley = true
		crystal_lakes = true
		windswept_cliffs = true
		meadows = true
		flooded_woodlands = true
		stony_fields = true

		#Biome Weights
		[Settings.Biomes."Biome Weights"]
			overgrown_spires_weight = 3
			verdant_sands_weight = 3
			boreal_forest_weight = 3
			snowy_boreal_forest_weight = 3
			redwoods_weight = 3
			snowy_redwoods_weight = 3
			redwood_peaks_weight = 3
			pine_meadows_weight = 3
			alpine_heights_weight = 3
			boreal_plateau_weight = 3
			aspen_grove_weight = 3
			mangrove_marsh_weight = 3
			willow_wetlands_weight = 3
			baobab_fields_weight = 3
			prairie_weight = 3
			blossoming_fields_weight = 3
			autumnal_coniferous_forest_weight = 3
			crimson_thicket_weight = 3
			desert_shrubland_weight = 3
			red_rock_valley_weight = 3
			crystal_lakes_weight = 3
			windswept_cliffs_weight = 3
			meadows_weight = 3
			flooded_woodlands_weight = 3
			stony_fields_weight = 3

		#Biome Ambience Settings
		[Settings.Biomes."Biome Ambience"]
			windswept_cliffs_particles = true

	[Settings."Mob Settings"]

		[Settings."Mob Settings"."Mob Toggles"]
			"Enable Flies" = false
			"Enable Fireflies" = false
			"Enable Starfish" = false
			"Enable Clams" = false
			"Enable Snails" = false
			"Enable Slugs" = false
			"Enable Small Spiders" = false
			"Enable Frogs" = false

			[Settings."Mob Settings"."Mob Toggles"."Mob Spawn Weights"]
				"Fly Spawn Weight" = 0
				"Firefly Spawn Weight" = 0
				"Starfish Spawn Weight" = 0
				"Clam Spawn Weight" = 0
				"Snail Spawn Weight" = 0
				"Slug Spawn Weight" = 0
				"Small Spider Spawn Weight" = 0
				"Frog Spawn Weight" = 0

		[Settings."Mob Settings"."Misc Mob Settings"]
			"Mute Flies" = false

		[Settings."Mob Settings"."Vanilla Mob Settings"]
			#Tropical fish in jungles
			jungleTropicalFish = true
			#Bats spawn outside at night
			nightBats = false

	#Tree Settings
	[Settings."Tree Settings"]
		enablePalmTrees = true
		enableJuniperTrees = true

