
#War of the Worlds Mod Config (Client-Side)
[WOTWMod]
	#Enable Developer Mode (Default: False)
	dev_ui = false
	#Enable or disable the custom title screen (Default: True)
	titleScreen = false
	#Enable or disable the custom item display at the top right (Default: True)
	item_overlay = false
	#Red Mist in the overworld (Default: True)
	red_fog_effect = true
	#Ammo counter when holding gun (Default: True)
	gun_overlay = true
	#Tooltips when looking at certain blocks (Default: True)
	block_tooltips = false
	#Music on the title screen (Default: True)
	title_screen_music = true

